SUPABASE_URL = "https://rvglsjiqpvxtdghzcvxi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2Z2xzamlxcHZ4dGRnaHpjdnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjQzODMsImV4cCI6MjA1NjE0MDM4M30.c-4RwrKEGGQwRtEmCuXx3nERLiwJrGgcY03Qkfo69CY"
